In [2]:
from numpy import *
import operator

def createDataSet(): 
    group = array ([[1.0, 1.1], [1.0,1.0],[0,0],[0,1.0]])
    labels = ['A', 'A', 'B', 'B']
    return group, labels

In [12]:
group, labels = createDataSet()

In [33]:
def classify0(inX, dataSet, labels, k): 
    dataSetSize = dataSet.shape[0]
    d = tile(inX, (dataSetSize, 1))
    print d
    diffMat = d- dataSet
    print diffMat
    sqDiffMat = diffMat**2
    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances**0.5
    sortedDistIndicies = distances.argsort()
    print sortedDistIndicies
    classCount = {}
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        print voteIlabel
        classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1
        print classCount
    sortedClassCount = sorted(classCount.iteritems(), key = operator.itemgetter(1), reverse = True)
    print sortedClassCount
    return sortedClassCount[0][0]

In [34]:
classify0([1.0,1.0], group, labels, 3)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 0.  -0.1]
 [ 0.   0. ]
 [ 1.   1. ]
 [ 1.   0. ]]
[1 0 3 2]
A
{'A': 1}
A
{'A': 2}
B
{'A': 2, 'B': 1}
[('A', 2), ('B', 1)]


'A'

In [35]:
import kNN